Horizontal compare
red6/pdfcompare pull request #93
Opened 2021-03-12 10:38 UTC by v3g3t4x

Added horizontal compare.
Gived 2 pdf generate a third pdf where for each page you can find on the left the page of first pdf and on the right the page of the second pdf.
Here an example on how use it...use **setEnableHorizontalCompareOutput**..

PdfComparator compare = new PdfComparator("input/input1.pdf", "input/input2.pdf");
		boolean flagLeftRight = true;
		compare.headerLeft = "LEFT";
		compare.headerRight = "RIGHT";

		compare.withEnvironment(new SimpleEnvironment().setActualColor(Color.red).setParallelProcessing(true)
				.setMaxImageSize(100000).setDocumentCacheSize(0).setOverallTimeout(15)
				.setExpectedColor(Color.CYAN).setAddEqualPagesToResult(true).setDPI(DPI)
				.setEnableHorizontalCompareOutput(flagLeftRight).setAllowedDiffInPercent(pixel));

		CompareResult result = compare.compare();

2021-03-13 12:03 UTC, nilimapradipm commented
Thanks a lot

2026-07-03 12:14 UTC, Greg0816 commented
I would love this feature!
I have to give the difference to our specialised department for review, but it's hard for them to read the squashed pixels and it's tedious for me to fetch the 'actual PDF' from within our systems.

2026-07-04 12:57 UTC, v3g3t4x commented
> I would love this feature! I have to give the difference to our specialised department for review, but it's hard for them to read the squashed pixels and it's tedious for me to fetch the 'actual PDF' from within our systems.

How I can help you?

2026-07-06 08:03 UTC, Greg0816 commented
> > I would love this feature! I have to give the difference to our specialised department for review, but it's hard for them to read the squashed pixels and it's tedious for me to fetch the 'actual PDF' from within our systems.
> 
> How I can help you?

I want to push your PR. Your feature would be very helpful for me. That's all :)

2026-07-06 08:25 UTC, v3g3t4x commented
> > > I would love this feature! I have to give the difference to our specialised department for review, but it's hard for them to read the squashed pixels and it's tedious for me to fetch the 'actual PDF' from within our systems.
> > 
> > 
> > How I can help you?
> 
> I want to push your PR. Your feature would be very helpful for me. That's all :)

I don't know why PR is still open. You can contact manteiner of repo.

2026-07-06 08:43 UTC, finsterwalder commented
Hi there,
this repo is not under very active development anymore. I hardly find time to work on it.
The PR has some flaws in code quality IMHO and is inconsistent to the existing code in some ways.
I didn't have the time to do a proper review or rework of the code. Sorry.
Maybe I find the time during the next two weeks.

2026-07-06 09:01 UTC, finsterwalder requested changes

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/env/ConfigFileEnvironment.java
> -        return config.getInt("imageCacheSizeCount");
This should not be set to a fixed value. Revert to the previous code, please

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/env/ConfigFileEnvironment.java
> +		return false;
Should not be a fixed value but should be read from the config instead, so it's configurable via a config file

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/env/SimpleEnvironment.java
> +    private Boolean enableHorizontalCompareOutput=false;
Should not be initialized to false here.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/env/SimpleEnvironment.java
> +		return enableHorizontalCompareOutput;
Should include fallback handling to be consistent with the config chain.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/AbstractCompareResultWithSwap.java
> +            LOG.info("Merging...");
Please leave this at trace level to reduce logging noise for normal users

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/AbstractCompareResultWithSwap.java
> +                    LOG.info("Swapping {} pages to disk", images.size());
Please leave this at trace level to reduce logging noise for normal users

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/AbstractCompareResultWithSwap.java
> +                    LOG.info("minPageIndex: {}", minPageIndex);
Please leave this at trace level to reduce logging noise for normal users

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/AbstractCompareResultWithSwap.java
> +                    LOG.info("Swapping took: {}ms", Duration.between(start, end).toMillis());
Please leave this at trace level to reduce logging noise for normal users

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> +		        //Creto una nuova immagine con a sinistra l'atteso e a destra l'attuale con segnate le differenze
Please only use english in code and comments

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> +		        this.hasDifferenceInExclusion |= diffCalculator.differencesFoundInExclusion();
This is duplicated code. Should be removed here.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> +			this.hasDifferenceInExclusion |= diffCalculator.differencesFoundInExclusion();
This code is duplicated in addPageWithHorizontalCompare.
Move this code before the if and remove in addPageWithHorizontalCompare.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> +		        }
This code is duplicated. Should be removed here.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/DiffImage.java
> +
No System.out.println. Please remove

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/DiffImage.java
> +                //this.salvaSuFileImmagine(actualBuffer, expectedBuffer);
Please remove commented out code.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/DiffImage.java
> +                expectedElement = getExpectedElement(x, y, expectedLineOffset);
Please remove trailing spaces

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/DiffImage.java
> +
This code is not called, so should be removed.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +			// System.out.println("maxHeight:" + maxHeight);
Remove commented out code

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +		ImageWithDimension nuovaImmag = null;
Please use only english in code and comments

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +			// File("output/combfinal.png"));
Please remove commented out code

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +			//ImageIO.write(left.getBufferedImage(), "PNG", new File("left.png"));
Please remove commented out code

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +			Graphics g = combined.getGraphics();
Please use more speaking name, like combinedGraphics

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +				Graphics leftG = left.getBufferedImage().getGraphics();
Please use a more speaking name, like leftGraphics

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +				Graphics rightG = right.getBufferedImage().getGraphics();
Please use a more speaking name, like rightGraphics

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> +        }else {
Please use the same formatting/spacing as the rest of the code

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +package x.team.tool;
Please use a package in de.red6.pdfcompare

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/poc/POC.java
> +}
Please write a proper integration test for this scenarios.
English in code and comments only please.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> +	public void addPageWithHorizontalCompare(PageDiffCalculator diffCalculator, int pageIndex,
This method is not unit tested. Please write tests for it.

2026-07-06 09:01 UTC, finsterwalder commented on src/main/java/x/team/tool/MergeImages.java
> +	public ImageWithDimension mergeOnLeft(ImageWithDimension left, ImageWithDimension right, String headerLeft,
This code is not unit tested. Please write tests for it.

2026-07-06 09:40 UTC, finsterwalder commented
@v3g3t4x I quickly added some immediate findings. Could you clean those up please?
Then I will look again in more detail. Thank you!

2026-07-06 12:15 UTC, Greg0816 requested changes

2026-07-06 12:15 UTC, Greg0816 commented on src/main/java/de/redsix/pdfcompare/DiffImage.java
> +            LOG.debug("Differences found at { page: {}, x1: {}, y1: {}, x2: {}, y2: {} }", page + 1, diffAreaX1, diffAreaY1, diffAreaX2,
Why did you change the log level?

2026-07-06 12:15 UTC, Greg0816 commented on src/main/java/de/redsix/pdfcompare/CompareResultImpl.java
> -        diffPercentages.put(pageIndex, diffCalculator.getDifferenceInPercent());
This line is missing in the else-block.

2026-07-07 07:40 UTC, Greg0816 commented
@v3g3t4x I want to support the development, if you wish. Please add me as maintainer to your PR.

edit: Most of the work is done, but i can't push to your PR. I hope we find a solution :)

2026-07-07 10:38 UTC, finsterwalder commented
@Greg0816 
I'm not at all a Github expert.
But I think there are two ways to approach this:
Either @v3g3t4x gives you access to the existing branch and PR.
But if that does not happen in time, you could simply fork again from @v3g3t4x branch and create a new PR.

2026-07-07 11:00 UTC, Greg0816 commented
> @Greg0816 I'm not at all a Github expert. But I think there are two ways to approach this: Either @v3g3t4x gives you access to the existing branch and PR. But if that does not happen in time, you could simply fork again from @v3g3t4x branch and create a new PR.

So am i ;-)
Thanks for your advise.

But he did most of the work, so i want to give him the credits. 
I'll wait about two more days, otherwise i'll fork.

2026-09-14 19:41 UTC, merged